# Default values for public-brands-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
eksCluster: false
replicaCount: 2
image:
  repository: coco/public-brands-api
  pullPolicy: IfNotPresent
env:
  app:
    port: "8080"
  cache:
    duration: "168h" #one week
resources:
  limits:
    memory: 128Mi
  requests:
    memory: 16Mi
